name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run PHP Security Checker
      uses: fabpot/local-php-security-checker@v1.0.0
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Secure Messenger'
        format: 'HTML'